movie_list = [
  [ "Star Wars", "action", 1977, "George Lucas", "Luke Skywalker joins forces with a Jedi Knight, a cocky pilot, a Wookiee and two droids to save the galaxy from the Empire's world-destroying battle station, while also attempting to rescue Princess Leia from the mysterious Darth Vader.", "https://i.etsystatic.com/16355321/r/il/f1da2e/1432871762/il_570xN.1432871762_kfjw.jpg", "vZ734NWnAHA"],
  [ "Star Wars: Episode V - The Empire Strikes Back", "action", 1980, "Irvin Kershner", "After the rebels are brutally overpowered by the Empire on the ice planet Hoth, Luke Skywalker begins Jedi training with Yoda, while his friends are pursued by Darth Vader.", "https://i.pinimg.com/736x/30/e9/68/30e968fe35c6aa71ded7f3ec456a0d84.jpg", "JNwNXF9Y6kY"],
  [ "Star Wars: Episode VI - Return of the Jedi", "action", 1983, "Richard Marquand", "After a daring mission to rescue Han Solo from Jabba the Hutt, the rebels dispatch to Endor to destroy a more powerful Death Star. Meanwhile, Luke struggles to help Darth Vader back from the dark side without falling into the Emperor's trap.", "https://http2.mlstatic.com/poster-peq-couche-a3-de-o-retornostar-wars-ep6-v11-D_NQ_NP_707955-MLB27753422843_072018-F.jpg", "5UfA_aKBGMc"],
  [ "Star Wars: Episode I - The Phantom Menace", "action", 1999, "George Lucas", "Two Jedi Knights escape a hostile blockade to find allies and come across a young boy who may bring balance to the Force, but the long dormant Sith resurface to claim their old glory.", "https://http2.mlstatic.com/poster-pequeno-imp-couche-a3-de-star-wars-ep-1-ver21-D_NQ_NP_937637-MLB27754883537_072018-F.jpg", "bD7bpG-zDJQ"],
  [ "Star Wars: Episode II - Attack of the Clones", "action", 2002, "George Lucas", "Ten years after initially meeting, Anakin Skywalker shares a forbidden romance with Padmé Amidala, while Obi-wan Kenobi investigates an assassination attempt on the Senator and discovers a secret clone army crafted for the Jedi.", "https://images-na.ssl-images-amazon.com/images/I/61nFfWio-sL._SY679_.jpg", "gYbW1F_c9eM"],
  [ "Star Wars: Episode III - Revenge of the Sith", "action", 2005, "George Lucas", "Three years into the Clone Wars, the Jedi rescue Palpatine from Count Dooku. As Obi-wan pursues a new threat, Anakin acts as a double agent between the Jedi Council and Palpatine and is lured into a sinister plan to rule the galaxy.", "https://images-na.ssl-images-amazon.com/images/I/61nAp2cNlbL._SY679_.jpg", "5UnjrG_N8hU"],
  [ "Harry Potter and the Sorcerer's Stone", "fantasy", 2001, "Chris Columbus", "An orphaned boy enrolls in a school of wizardry, where he learns the truth about himself, his family and the terrible evil that haunts the magical world.", "https://m.media-amazon.com/images/M/MV5BNjQ3NWNlNmQtMTE5ZS00MDdmLTlkZjUtZTBlM2UxMGFiMTU3XkEyXkFqcGdeQXVyNjUwNzk3NDc@._V1_UY1200_CR90,0,630,1200_AL_.jpg", "VyHV0BRtdxo"],
  [ "The Lord of the Rings: The Fellowship of the Ring", "fantasy", 2001, "Peter Jackson", "A meek Hobbit from the Shire and eight companions set out on a journey to destroy the powerful One Ring and save Middle-earth from the Dark Lord Sauron.", "https://m.media-amazon.com/images/M/MV5BN2EyZjM3NzUtNWUzMi00MTgxLWI0NTctMzY4M2VlOTdjZWRiXkEyXkFqcGdeQXVyNDUzOTQ5MjY@._V1_.jpg", "V75dMMIW2B4"],
  [ "The Godfather", "drama", 1972, "Francis Ford Coppola", "The aging patriarch of an organized crime dynasty transfers control of his clandestine empire to his reluctant son.", "https://images-na.ssl-images-amazon.com/images/I/418vBoKURIL.jpg", "sY1S34973zA"],
  [ "Pulp Fiction", "drama", 1994, "Quentin Tarantino", "The lives of two mob hitmen, a boxer, a gangster's wife, and a pair of diner bandits intertwine in four tales of violence and redemption.", "https://uauposters.com.br/media/catalog/product/cache/1/image/9df78eab33525d08d6e5fb8d27136e95/0/4/047620140408-posters-filmes-retro-pulp-fiction-tarantino.jpg", "s7EdQ4FqbhY"],
  [ "The Matrix", "scifi", 1999, "The Wachowski Brothers", "A computer hacker learns from mysterious rebels about the true nature of his reality and his role in the war against its controllers.", "https://http2.mlstatic.com/pster-matrix-papel-fotografico-a3-p1096-D_NQ_NP_846083-MLB26580614521_122017-F.jpg", "2KnZac176Hs"],
  [ "Midnight in Paris", "comedy", 2011, "Woody Allen", "While on a trip to Paris with his fiancée's family, a nostalgic screenwriter finds himself mysteriously going back to the 1920s everyday at midnight.", "https://cdn.shopify.com/s/files/1/1057/4964/products/midnight-in-paris-vintage-movie-poster-original-french-1-panel-47x63-4056.jpg?v=1534401981", "FAfR8omt-CY"],
  [ "About Time", "comedy", 2013, "Richard Curtis", "At the age of 21, Tim discovers he can travel in time and change what happens and has happened in his own life. His decision to make his world a better place by getting a girlfriend turns out not to be as easy as you might think.", "https://imgc.allpostersimages.com/img/print/posters/about-time-rachel-mcadams-domhnall-gleeson-movie-poster_a-G-9812909-0.jpg", "T7A810duHvw"],
  [ "Mr. Nobody", "fantasy", 2009, "Jaco Van Dormael", "A boy stands on a station platform as a train is about to leave. Should he go with his mother or stay with his father? Infinite possibilities arise from this decision. As long as he doesn't choose, anything is possible.", "https://upload.wikimedia.org/wikipedia/pt/3/32/Mr._Nobody_%28film_poster%29.jpg", "vXf3gVYXlHg"],
  [ "The Butterfly Effect", "scifi", 2004, "J. Mackye Gruber", "Evan Treborn suffers blackouts during significant events of his life. As he grows up, he finds a way to remember these lost memories and a supernatural way to alter his life by reading his journal.", "https://images.wolfgangsvault.com/the-butterfly-effect/poster/m/ZZZ061131-PO.jpg", "B8_dgqfPXFg"]
]

movie_list.each do |title, main_genre, release_year, director, description, photo_url, youtube_id|
  Movie.create(title: title, main_genre: main_genre, release_year: release_year, director: director, description: description, photo_url: photo_url, youtube_id: youtube_id)
end
